# mysql connect info
[MysqlConn]
mysqlHost=up01
mysqlPort=3306
mysqlUName=root
mysqlPassWord=123456
# kafka connect info
[KafkaConn]
bootstrapServerHost=up01
bootstrapServerPort=9092
event_topic=hmzx_user_event
nginx_topic=hmzx_nginx_log